import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { Background } from "@/components/section/backGround/Style";
import { TanstackProvider } from "@/providers/tanstackProvider";
import { WebSocketProvider } from "@/providers/webSocketProvider";
import { Toaster } from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Background>
          <WebSocketProvider>
            <TanstackProvider>
              <NextAuthProvider session={session}>
                {children}
                <Toaster />
              </NextAuthProvider>
            </TanstackProvider>
          </WebSocketProvider>
        </Background>
      </body>
    </html>
  );
}
